'SPDX-License-Identifier: CC-BY-4.0
@startuml
skinparam componentStyle rectangle
skinparam linetype ortho

package "trigger"{ 
[Telltale Requester]
[Ignition]
[Battery]
}
package "SoC" {
  [Cluster Controller] -up-> [Image Generator] 
  [Image Generator] -down-> [Cluster Controller]
 
  [Cluster Controller] <-left- [Telltale Requester]
  [Cluster Controller] <-left- [Ignition]
  [Cluster Controller] <-left- [Battery]
}
package "Display" {
  [Display IC] <-l- [Image Generator] : image
  [Display IC] <-r- [Cluster Controller] : Telltale\ninformation
  [Display IC] -r-> [Cluster Controller] : Safety line
  [TFT] -> [Display IC] : Diagnostics
  [TFT] <- [Display IC] : Image
  [Backlight] <-- [Cluster Controller]: backlight\nkill line
}
[Watchdog] -u- [Cluster Controller]
@enduml
